### ISSUE TITLE
Btn-icon ändern

### ISSUE THREAD

**Issue by ClemensDel** [ChrislerOne/djangoImpfVergabe#32]
Auf den btn beim Impfübersicht muss ein Button icon geändert werden

**Comment by ChrislerOne** [comment]
Bitte was?

**Comment by ChrislerOne** [comment]
@ClemensDel

**Comment by ClemensDel** [comment]
Auf einer Seite war falscher Text auf dem Button. Das kann ich auch machen

**Comment by ClemensDel** [comment]
- [ ] search zu suchen 
- [ ] mode_edit zu bootstrap icon
- [ ] messeage wenn Mitarbeiter Termin bucht
